commit 275aedccd4f2beae82dbf96c94a6c1c9b365a647
Author: Bryan C. Mills <bcmills@google.com>
Date:   Tue Feb 8 15:07:21 2022 -0500

    runtime: skip TestGdbBacktrace flakes matching a known GDB internal error
    
    TestGdbBacktrace occasionally fails due to a GDB internal error.
    We have observed the error on various linux builders since at least
    October 2020, and it has been reported upstream at least twice.¹²
    
    Since the bug is external to the Go project and does not appear to be
    fixed upstream, this failure mode can only add noise.
    
    ¹https://sourceware.org/bugzilla/show_bug.cgi?id=24628
    ²https://sourceware.org/bugzilla/show_bug.cgi?id=28551
    
    Fixes #43068
    
    Change-Id: I6c92006a5d730f1c4df54b0307f080b3d643cc6b
    Reviewed-on: https://go-review.googlesource.com/c/go/+/384234
    Trust: Bryan Mills <bcmills@google.com>
    Run-TryBot: Bryan Mills <bcmills@google.com>
    Reviewed-by: Michael Pratt <mpratt@google.com>
    TryBot-Result: Gopher Robot <gobot@golang.org>
---
 src/runtime/runtime-gdb_test.go | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/src/runtime/runtime-gdb_test.go b/src/runtime/runtime-gdb_test.go
index 7e8723e15f..2de613c7d3 100644
--- a/src/runtime/runtime-gdb_test.go
+++ b/src/runtime/runtime-gdb_test.go
@@ -427,6 +427,9 @@ func TestGdbBacktrace(t *testing.T) {
 	got, err := testenv.RunWithTimeout(t, exec.Command("gdb", args...))
 	t.Logf("gdb output:\n%s", got)
 	if err != nil {
+		if bytes.Contains(got, []byte("internal-error: wait returned unexpected status 0x0")) {
+			testenv.SkipFlaky(t, 43068)
+		}
 		t.Fatalf("gdb exited with error: %v", err)
 	}
 
